import type { GetStaticProps } from "next";
import { signIn } from "next-auth/react";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";

const Landing = () => {
  return (
    <>
      <Head>
        <title>ASM V2</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-zinc-800">
        <section className="flex grow flex-col pb-0">
          <div className="p-10 sm:p-16">
            <h1 className="tracking-super-wide m-0 text-center text-2xl font-bold sm:mb-16 sm:text-6xl md:text-5xl">
              <span className="text-slate-100 ">Advanced </span>
              <span className="text-primary">Spotify </span>
              <span className="text-slate-100 ">Manager</span>
            </h1>
          </div>

          <Features />
        </section>
        <Footer />
      </main>
    </>
  );
};

export default Landing;

const Features = () => {
  const { t } = useTranslation("landing");

  return (
    <section className="flex grow flex-col text-center text-gray-800 md:text-left">
      <div className=" diagonal grid grow place-items-center p-10 pb-16 text-white">
        <div className="grid gap-2 text-center">
          <h1 className="mb-2 text-2xl font-extrabold">{t("create")}</h1>
          <h2 className="text-xl">{t("templates-1")}</h2>
          <h2 className="text-xl">{t("templates-2")}</h2>
        </div>
      </div>
      <div className="grid grow place-items-center p-10 pt-16 pb-16 font-medium text-white">
        <div className="grid gap-2 text-center">
          <h1 className="mb-2 text-2xl font-extrabold">{t("explore")}</h1>
          <h2 className="text-xl">{t("stats-1")}</h2>
          <h2 className="text-xl">{t("stats-2")}</h2>
          <h2 className="text-xl">{t("stats-3")}</h2>
        </div>
      </div>
      <div className="diagonal-green grid flex-grow place-items-center p-10  pb-16 text-white">
        <div className="grid gap-2 text-center">
          <h1 className="mb-2 text-2xl font-extrabold ">{t("surprise")}</h1>
          <h2 className="text-xl">{t("share")}</h2>
        </div>{" "}
      </div>
      <div className="mb-8 flex w-full grow items-center justify-center">
        <button
          className="mt-16 w-max rounded-full bg-primary px-10 py-3 font-semibold  text-gray-900 no-underline"
          onClick={() => signIn("spotify", { callbackUrl: "/home" })}
        >
          Get Started
        </button>
      </div>
    </section>
  );
};
const Footer = () => {
  return (
    <footer className="pb-4 text-gray-400">
      <div className=" flex justify-center pt-3 pb-5">
        <span className="mt-4 inline-flex items-center justify-end sm:mt-0">
          <p className=" mr-4 text-sm text-gray-400 sm:ml-4 sm:mt-0   sm:border-gray-800">
            Dario Puddinu 2023
          </p>
          <a className="text-gray-400">
            <svg
              fill="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              className="h-5 w-5"
              viewBox="0 0 24 24"
            >
              <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
            </svg>
          </a>
          <a className="ml-3 text-gray-400">
            <svg
              fill="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              className="h-5 w-5"
              viewBox="0 0 24 24"
            >
              <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
            </svg>
          </a>
          <a className="ml-3 text-gray-400">
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              className="h-5 w-5"
              viewBox="0 0 24 24"
            >
              <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
              <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
            </svg>
          </a>
          <a className="ml-3 text-gray-400">
            <svg
              fill="currentColor"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="0"
              className="h-5 w-5"
              viewBox="0 0 24 24"
            >
              <path
                stroke="none"
                d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"
              ></path>
              <circle cx="4" cy="4" r="2" stroke="none"></circle>
            </svg>
          </a>
        </span>
      </div>
    </footer>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale ?? "en", ["landing"])),
  },
});
